
// adapted from: 
// states_hash.json on GitHub Gist:
// https://gist.github.com/mshafrir/2646763#file-states_hash-json

var jsonDocument = '{ "AL": "Alabama", "AK": "Alaska", "AS": "American Samoa", "AZ": "Arizona", "AR": "Arkansas", "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware", "DC": "District Of Columbia", "FM": "Federated States Of Micronesia", "FL": "Florida", "GA": "Georgia", "GU": "Guam", "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MH": "Marshall Islands", "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi", "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "MP": "Northern Mariana Islands", "OH": "Ohio", "OK": "Oklahoma", "OR": "Oregon", "PW": "Palau", "PA": "Pennsylvania", "PR": "Puerto Rico", "RI": "Rhode Island", "SC": "South Carolina", "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont", "VI": "Virgin Islands", "VA": "Virginia", "WA": "Washington", "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming" }' ;



// adapted from
// http://stackoverflow.com/questions/1650090/javascript-multi-level-array-of-json-objects-how-to-access-key-value-pair-in-s

var jsonDocument_multi = '[{"title": "Parent1", "children": [{"childname": "Child11"}, {"childname":"Child12"}], "cars":[{"carname": "Car11"}, {"carname": "Car12"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] },{"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}] }, {"title": "Parent2", "children": [{"childname": "Child21"}, {"childname": "Child22"}], "cars": [{"carname": "Car21"}, {"carname": "Car22"}]}]';
